# example of build_database_node parameters set up

set_size: 100000

batch_size: 50

sampling_rate: 20 # Hertz

crowdy: false

pos_update_threshold: 0.005 # meters

step_resolution: 0.15

target_tolerance: 0.15

# better give absolute paths
base_path: /home/leonida/ThesisCode/LSTM_on_Create2/NavDatabases/

averaged_ranges_size: 24

# whether or not net has trained with command tail as input
steer_feedback: true

# resolution of allowed steering angles [degrees]
yaw_resolution: 30

# biasing the distance info
dist_preweight: 50
angle_preweight: 1

# database backend type {leveldb, lmdb} allowed
database_backend: lmdb

logs_path: /home/leonida/ThesisCode/LSTM_on_Create2/logs/ 
