# example of build_database_node parameters set up

set_size: 100000

batch_size: 50

sampling_rate: 2 # Hertz

pos_update_threshold: 0.005 # meters

step_resolution: 0.10

target_tolerance: 0.35

# better give absolute paths
base_path: /home/leonida/ThesisCode/LSTM_on_Create2/NavDatabases/

averaged_ranges_size: 12

# whether or not net has trained with command tail as input
steer_feedback: false

# resolution of allowed steering angles [degrees]
steer_resolution: 15

min_steer_angle: -45
max_steer_angle: 45

# biasing the distance info
dist_scale: 1

yaw_scale: 25

# database backend type {leveldb, lmdb} allowed
database_backend: lmdb

logs_path: /home/leonida/ThesisCode/LSTM_on_Create2/logs/ 
