# example of build_database_node parameters set up

set_size: 100000

batch_size: 50

sampling_rate: 30 # Hertz

crowdy: false

pos_update_threshold: 0.005 # meters

target_tolerance: 0.15

# better give absolute paths
base_path: /home/leonida/ThesisCode/LSTM_on_Create2/NavDatabases/

averaged_ranges_size: 24

# whether or not net has trained with command tail as input
command_feedback: true

# if command_feedback is true the type of the feedback {measured, reference}
feedback_type: measured 

# output size:
# - 1 means just angular vel is generated
# - 2 means both angular and translational vel are generated
output_size: 2

dist_preweight: 10

# database backend type {leveldb, lmdb} allowed
database_backend: lmdb

logs_path: /home/leonida/ThesisCode/LSTM_on_Create2/logs/ 
