# example of online deployment parameters set up

trained: /home/leonida/ThesisCode/LSTM_on_Create2/src/neural_network_planner/NetModels/LSTM/Snapshots/stack-fc/yaw/LSTM_deep-regression-3-64-16-27_iter_550000.caffemodel

online_model: /home/leonida/ThesisCode/LSTM_on_Create2/src/neural_network_planner/NetModels/LSTM/deep_stack-fc_online.prototxt

GPU: false

control_rate: 0.5 # Hertz

pos_update_threshold: 0.01 # meters

target_tolerance: 0.3

averaged_ranges_size: 20

# if it is a multi classification net
multiclass: true

# classes yaw resolution [degrees]
yaw_resolution: 15

min_steer_angle: -90
max_steer_angle: 90

# add the previous action to the input state
steer_feedback: false

# translational velocity limits
cruise_vel: 0.2
min_cruise_vel: 0.05

# rotational velocity limits
min_rotate_vel: 0.1
max_rotate_vel: 1

# if true publish state ranges as lines, false means only points 
show_lines: true

time_sequence: 10

logs_path: /home/leonida/ThesisCode/LSTM_on_Create2/logs/ 
