# example of train and validate parameters setting
# it is always better to write absolute paths of files needed
# you never know from which location you launch the process

train_set_size: 251

validate_set_size: 194

resume: false

validation_test_frequency: 3

solver_config: /home/leonida/ThesisCode/realenv-folder/NN-Roomba/RealEnv/src/neural_network_planner/NetModels/LSTM/deep_lstm_solver.prototxt

trained_weights: /home/leonida/ThesisCode/realenv-folder/NN-Roomba/RealEnv/src/neural_network_planner/NetModels/LSTM/deep_stack-bn_iter.caffemodel

GPU: true

epochs: 1000

time_sequence: 10

move_rad_distance: 1.57

folder_path: /home/leonida/ThesisCode/realenv-folder/NN-Roomba/RealEnv/src/neural_network_planner/NetModels/

averaged_ranges_size: 24
