# example of train and validate parameters setting
# it is always better to write absolute paths of files needed
# you never know from which location you launch the process

train_set_size: 50017

validate_set_size: 20372

resume: false

validation_test_frequency: 3

solver_config: /home/leonida/ThesisCode/LSTM_on_Create2/src/neural_network_planner/NetModels/LSTM/deep_lstm_solver.prototxt

trained_weights: /home/leonida/ThesisCode/LSTM_on_Create2/src/neural_network_planner/NetModels/LSTM/deep_stack_iter.caffemodel

GPU: true

epochs: 2000

time_sequence: 10

folder_path: /home/leonida/ThesisCode/LSTM_on_Create2/src/neural_network_planner/NetModels/

averaged_ranges_size: 24

# whether or not dataset has command tail as input
command_feedback: true

# if command_feedback is true the type of the feedback {measured, reference}
feedback_type: measured 

# output size:
# - 1 means just angular vel is generated
# - 2 means both angular and translational vel are generated
output_size: 2


logs_path: /home/leonida/ThesisCode/LSTM_on_Create2/logs/ 
